{
  "type": "service_account",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-bot%40crucial-engine-459814-t7.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
